server:
  port: 9090
spring:
  application:
    name: customer
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.bilibili.consumer.configuration.NacosWeightedRule #com.netflix.loadbalancer.RandomRule